# Generated by Django 3.2.4 on 2021-11-10 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='password1',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='password2',
            new_name='Repeat_Password',
        ),
    ]
